# Generated by Django 5.0.14 on 2026-06-17 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_producto_activo_producto_forma_producto_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vto', to='inventario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento VTO',
                'verbose_name_plural': 'Eventos VTO',
                'ordering': ['-timestamp'],
            },
        ),
    ]
